import type { Area } from "../../../domain/areas/areaTypes.js";
import type { PropertySourceRecord } from "../../../domain/properties/propertyTypes.js";

export const prototypeAreas: Area[] = [
  {
    area_id: "barranquilla",
    country_code: "CO",
    area_type: "city",
    display_name: "Barranquilla",
    city_name: "Barranquilla",
    description: "City-level prototype area for Barranquilla.",
    parent_area_id: null,
    centroid_latitude: 10.9878,
    centroid_longitude: -74.7889,
    zoom: 12,
    bounding_box: null,
    geometry_reference: null,
  },
  {
    area_id: "alto-prado",
    country_code: "CO",
    area_type: "neighborhood",
    display_name: "Alto Prado",
    city_name: "Barranquilla",
    description: "Named prototype area around Alto Prado.",
    parent_area_id: "barranquilla",
    centroid_latitude: 11.004,
    centroid_longitude: -74.811,
    zoom: 14,
    bounding_box: null,
    geometry_reference: null,
  },
  {
    area_id: "riomar",
    country_code: "CO",
    area_type: "neighborhood",
    display_name: "Riomar",
    city_name: "Barranquilla",
    description: "Named prototype area around Riomar.",
    parent_area_id: "barranquilla",
    centroid_latitude: 11.016,
    centroid_longitude: -74.825,
    zoom: 14,
    bounding_box: null,
    geometry_reference: null,
  },
  {
    area_id: "villa-santos",
    country_code: "CO",
    area_type: "neighborhood",
    display_name: "Villa Santos",
    city_name: "Barranquilla",
    description: "Named prototype area around Villa Santos.",
    parent_area_id: "barranquilla",
    centroid_latitude: 11.01,
    centroid_longitude: -74.836,
    zoom: 14,
    bounding_box: null,
    geometry_reference: null,
  },
  {
    area_id: "sample-empty-area",
    country_code: "CO",
    area_type: "neighborhood",
    display_name: "Sample Empty Area",
    city_name: "Barranquilla",
    description: "Prototype area used to verify empty explorer responses.",
    parent_area_id: "barranquilla",
    centroid_latitude: 11,
    centroid_longitude: -74.8,
    zoom: 14,
    bounding_box: null,
    geometry_reference: null,
  },
];

export const prototypeProperties: PropertySourceRecord[] = [
  {
    property_id: "baq-001",
    country_code: "CO",
    city_name: "Barranquilla",
    area_id: "alto-prado",
    neighborhood_name: "Alto Prado",
    locality_name: null,
    address_label: "Carrera 54 near Parque Washington",
    listing_url: "https://example.com/rent-yield/listings/baq-001",
    latitude: 11.0061,
    longitude: -74.8097,
    property_type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    interior_area_sqm: 82,
    sale_price_amount: 420_000_000,
    sale_price_currency: "COP",
    monthly_rent_amount: 2_800_000,
    monthly_rent_currency: "COP",
    listing_status: "for_sale",
    rent_source_type: "estimated_model",
    sale_price_source_type: "observed_listing",
    observed_at: null,
  },
  {
    property_id: "baq-002",
    country_code: "CO",
    city_name: "Barranquilla",
    area_id: "alto-prado",
    neighborhood_name: "Alto Prado",
    locality_name: null,
    address_label: "Calle 79 corridor apartment",
    listing_url: "https://example.com/rent-yield/listings/baq-002",
    latitude: 11.0019,
    longitude: -74.8114,
    property_type: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    interior_area_sqm: 118,
    sale_price_amount: 680_000_000,
    sale_price_currency: "COP",
    monthly_rent_amount: 3_900_000,
    monthly_rent_currency: "COP",
    listing_status: "for_sale",
    rent_source_type: "observed_listing",
    sale_price_source_type: "observed_listing",
    observed_at: null,
  },
  {
    property_id: "baq-003",
    country_code: "CO",
    city_name: "Barranquilla",
    area_id: "riomar",
    neighborhood_name: "Riomar",
    locality_name: null,
    address_label: "Buenavista area high-rise",
    listing_url: "https://example.com/rent-yield/listings/baq-003",
    latitude: 11.0142,
    longitude: -74.8272,
    property_type: "apartment",
    bedrooms: 1,
    bathrooms: 2,
    interior_area_sqm: 58,
    sale_price_amount: 310_000_000,
    sale_price_currency: "COP",
    monthly_rent_amount: 2_400_000,
    monthly_rent_currency: "COP",
    listing_status: "for_sale",
    rent_source_type: "estimated_model",
    sale_price_source_type: "observed_listing",
    observed_at: null,
  },
  {
    property_id: "baq-004",
    country_code: "CO",
    city_name: "Barranquilla",
    area_id: "riomar",
    neighborhood_name: "Riomar",
    locality_name: null,
    address_label: "Riomar family apartment",
    listing_url: "https://example.com/rent-yield/listings/baq-004",
    latitude: 11.0181,
    longitude: -74.8234,
    property_type: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    interior_area_sqm: 132,
    sale_price_amount: 790_000_000,
    sale_price_currency: "COP",
    monthly_rent_amount: 4_400_000,
    monthly_rent_currency: "COP",
    listing_status: "for_sale",
    rent_source_type: "observed_listing",
    sale_price_source_type: "observed_listing",
    observed_at: null,
  },
  {
    property_id: "baq-005",
    country_code: "CO",
    city_name: "Barranquilla",
    area_id: "villa-santos",
    neighborhood_name: "Villa Santos",
    locality_name: null,
    address_label: "Villa Santos compact apartment",
    listing_url: "https://example.com/rent-yield/listings/baq-005",
    latitude: 11.0114,
    longitude: -74.835,
    property_type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    interior_area_sqm: 72,
    sale_price_amount: 365_000_000,
    sale_price_currency: "COP",
    monthly_rent_amount: 2_650_000,
    monthly_rent_currency: "COP",
    listing_status: "for_sale",
    rent_source_type: "estimated_model",
    sale_price_source_type: "observed_listing",
    observed_at: null,
  },
  {
    property_id: "baq-006",
    country_code: "CO",
    city_name: "Barranquilla",
    area_id: "villa-santos",
    neighborhood_name: "Villa Santos",
    locality_name: null,
    address_label: "Villa Santos townhouse",
    listing_url: "https://example.com/rent-yield/listings/baq-006",
    latitude: 11.0092,
    longitude: -74.8376,
    property_type: "house",
    bedrooms: 4,
    bathrooms: 4,
    interior_area_sqm: 188,
    sale_price_amount: 980_000_000,
    sale_price_currency: "COP",
    monthly_rent_amount: 5_200_000,
    monthly_rent_currency: "COP",
    listing_status: "for_sale",
    rent_source_type: "observed_listing",
    sale_price_source_type: "observed_listing",
    observed_at: null,
  },
  {
    property_id: "baq-007",
    country_code: "CO",
    city_name: "Barranquilla",
    area_id: "barranquilla",
    neighborhood_name: "El Prado",
    locality_name: null,
    address_label: "El Prado renovated studio",
    listing_url: "https://example.com/rent-yield/listings/baq-007",
    latitude: 10.9977,
    longitude: -74.7974,
    property_type: "studio",
    bedrooms: 1,
    bathrooms: 1,
    interior_area_sqm: 44,
    sale_price_amount: 210_000_000,
    sale_price_currency: "COP",
    monthly_rent_amount: 1_650_000,
    monthly_rent_currency: "COP",
    listing_status: "for_sale",
    rent_source_type: "estimated_model",
    sale_price_source_type: "manual_import",
    observed_at: null,
  },
  {
    property_id: "baq-008",
    country_code: "CO",
    city_name: "Barranquilla",
    area_id: "barranquilla",
    neighborhood_name: "Miramar",
    locality_name: null,
    address_label: "Miramar balcony apartment",
    listing_url: "https://example.com/rent-yield/listings/baq-008",
    latitude: 11.0053,
    longitude: -74.8195,
    property_type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    interior_area_sqm: 76,
    sale_price_amount: 340_000_000,
    sale_price_currency: "COP",
    monthly_rent_amount: 2_300_000,
    monthly_rent_currency: "COP",
    listing_status: "for_sale",
    rent_source_type: "historical_observed",
    sale_price_source_type: "observed_listing",
    observed_at: null,
  },
];
